### ISSUE TITLE
数据tfrecord到pickle格式转换

### ISSUE THREAD

**Issue by BroJackfeely** [baidu/Youtube-8M#1]
可以release对于Youtube-8M frame-level feature数据，从tfrecords格式到pickle格式转换的代码吗？

**Comment by CrossLee1** [comment]
@BroJackfeely 已将从tfrecords格式到pickle格式转换的代码放到tools目录下，请注意查看。
多谢关注~

**Comment by BroJackfeely** [comment]
!非常感谢！

还有一个问题想请教您，定义rgb_feature， audio_feature和label的input_type时，该如何声明？

e.g.
我的版本如下：
settings.input_types = {'rgb_feature': dense_vector(1024,
seq_type=SequenceType.SEQUENCE),
'audio_feature': dense_vector(128,
seq_type=SequenceType.SEQUENCE),
'label': sparse_binary_vector(4716,
seq_type=SequenceType.NO_SEQUENCE)}
其中rgb_feature, audio_feature维度分别为1024x300， 128x300.

**Comment by CrossLee1** [comment]
上面的版本应该是正确的

**Comment by BroJackfeely** [comment]
...................I1107 02:25:11.023088   586 TrainerInternal.cpp:182]  Pass=0 Batch=19 samples=1169 AvgCost=362.829 Eval:
F1107 02:25:11.222492   586 PyDataProvider.cpp:368] Check failed: (obj) != nullptr Current PYTHONPATH: ['/usr/local/opt/paddle/bin', '/media', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
Python Error: <type 'exceptions.IndexError'> : list index out of range
Python Callstack:
            /usr/local/lib/python2.7/dist-packages/paddle/trainer/PyDataProviderWrapper.py : 365
            /usr/local/lib/python2.7/dist-packages/paddle/trainer/PyDataProviderWrapper.py : 532
            /usr/local/lib/python2.7/dist-packages/paddle/trainer/PyDataProviderWrapper.py : 483
Call function getNextBatch failed.
*** Check failure stack trace: ***
    @     0x7fa5f4f27daa  (unknown)
    @     0x7fa5f4f27ce4  (unknown)
    @     0x7fa5f4f276e6  (unknown)
    @     0x7fa5f4f2a687  (unknown)
    @           0x53480e  paddle::PyDataProvider::getNextBatchInternal()
    @           0x53bb62  paddle::DataProvider::getNextBatch()
    @           0x693bff  paddle::Tester::testOnePeriod()
    @           0x677665  paddle::Trainer::finishTrainPass()
    @           0x679e7c  paddle::Trainer::trainOnePass()
    @           0x67b0d0  paddle::Trainer::train()
    @           0x513367  main
    @     0x7fa5f4133f45  (unknown)
    @           0x51f2a5  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 109:   586 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

在train.list中只放了一个.pkl文件， i.e. train-0.pkl, 里面包含了1169个video samples，batch_size = 64但是每次训练每个pass结束时都会报错，报错 getNextBatch failed。。。无法保存layer parameters进入下一个pass。。。

**Comment by CrossLee1** [comment]
看上去是test的时候报错了，你有指定test.list么，test.list里面有数据么

**Comment by BroJackfeely** [comment]
已解决，确实是test数据的问题。指定了test.list，里面包含的test-0.tfrecord对应的test-0.pkl，换成train-0.pkl即可跑通，回头我再检查一下这两个数据。

p.s. 我自己写了一个用api取每一层参数的脚本， convert data好像一直有问题。不太清楚怎么把数据和input_types一一对应起来。

报错信息如下：
Traceback (most recent call last):
  File "broj_api_predict.py", line 90, in <module>
    inArg = converter((rgb_feat, audio_feat, [label]))
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 157, in __call__
    return self.convert(dat, argument)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 149, in convert
    scanner.scan(each_step)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 115, in scan
    self.__inner_scanner__.scan(each)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 42, in scan
    self.__mat__.extend(dat)
TypeError: 'float' object is not iterable

脚本如下：
#------------------------------------------------------------------#
def _generate_test_data(filename, indx):
......
        feat_list = []
        audio_list = []
        for row in range(rgb_decode.shape[0]):
            feat_list.append(rgb_decode[row,:].tolist())
            audio_list.append(audio_decode[row,:].tolist())

        return (feat_list, audio_list, label)
#------------------------------------------------------------------------------------------#

swig_paddle.initPaddle("--use_gpu=0")

cfg = "trainer_config.conf"
conf = parse_config(cfg, "is_predict=1")

network = swig_paddle.GradientMachine.createFromConfigProto(conf.model_config)
assert isinstance(network, swig_paddle.GradientMachine)

# # load pre-trained model into bidi-lstm network
param = "./two_stream_lstm_models/pass-00000"
network.loadParameters(param)

converter = DataProviderConverter([dense_vector(1024, seq_type=SequenceType.SEQUENCE), dense_vector(128, seq_type=SequenceType.SEQUENCE), sparse_binary_vector(4716,seq_type=SequenceType.NO_SEQUENCE)])
[rgb_feat, audio_feat, label] = _generate_test_data('/media/data/train/train-0.pkl', 0)

inArg = converter((rgb_feat, audio_feat, [label]))
network.forwardTest(inArg)
output_layer = "__bidirectional_lstm_0__"
output = network.getLayerOutputs(output_layer)
res = output[output_layer]['value']
#---------------------------------------------------------------------------------------------------#

**Comment by CrossLee1** [comment]
inArg = converter((rgb_feat, audio_feat, [label]))
改为
inArg = converter([[rgb_feat, audio_feat, [label]]])
试下~

**Comment by BroJackfeely** [comment]
Error:

Traceback (most recent call last):
  File "broj_api_predict.py", line 90, in <module>
    inArg = converter([[rgb_feat, audio_feat, [label]]])
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 157, in __call__
    return self.convert(dat, argument)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 152, in convert
    scanner.finish_scan(argument)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 120, in finish_scan
    self.__inner_scanner__.finish_scan(argument)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 49, in finish_scan
    self.input_type.dim, False)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 583, in createDense
    return _swig_paddle.Matrix_createDense(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'Matrix_createDense'.
  Possible C/C++ prototypes are:
    Matrix::createDense(std::vector< float,std::allocator< float > > const &,size_t,size_t,bool)
    Matrix::createDense(std::vector< float,std::allocator< float > > const &,size_t,size_t)

**Comment by BroJackfeely** [comment]
以下是完整测试代码：

from py_paddle import swig_paddle, DataProviderConverter
from paddle.trainer.PyDataProvider2 import *
# from paddle.trainer.PyDataProviderWrapper import IndexSlot, provider, DenseSlot, SparseNonValueSlot 
from paddle.trainer.config_parser import parse_config
import os
import sys
import logging
import cPickle
import random
import numpy as np

# test data preparation
def Dequantize(feat_vector, max_quantized_value=2, min_quantized_value=-2):
    """
    Dequantize the feature from the byte format to the float format
    """

    assert max_quantized_value >  min_quantized_value
    quantized_range = max_quantized_value - min_quantized_value
    scalar = quantized_range / 255.0
    bias = (quantized_range / 512.0) + min_quantized_value
    
    return feat_vector * scalar + bias

def _generate_test_data(filename, indx):

    #--------------------------------------------------------------#
    #--- Function:
    #              _generate_test_data
    #---           e.g. load test-0.pkl data
    #--- Input:
    #---           [1] filename
    #---           [2] indx: index of video in .pkl file
    #--- Output:
    #---           return (rgb_feature, audio_feature, [label])
    #--------------------------------------------------------------#

    inp = open(filename, 'r')
    data = cPickle.load(inp)
    inp.close()

    indexes = range(len(data))
    random.shuffle(indexes)
    
    for i in indexes:
        record = data[i]
        nframes = record['nframes']
        rgb   = record['feature']
        audio = record['audio']
        label = record['label']
        video = record['video']
			
        rgb = rgb[0:nframes,:]
        rgb_decode = Dequantize(rgb, 2, -2)
        rgb_decode = rgb_decode.astype(np.float32)

        audio = audio[0:nframes,:]
        audio_decode = Dequantize(audio, 2, -2)
        audio_decode = audio_decode.astype(np.float32)

        feat_list = []
        audio_list = []
        for row in range(rgb_decode.shape[0]):
            feat_list.append(rgb_decode[row,:])
            audio_list.append(audio_decode[row,:])

        return (feat_list, audio_list, label)
#-----------------------------------------------------------------------------#

swig_paddle.initPaddle("--use_gpu=0")

cfg = "trainer_config.conf"
conf = parse_config(cfg, "is_predict=1")

network = swig_paddle.GradientMachine.createFromConfigProto(conf.model_config)
assert isinstance(network, swig_paddle.GradientMachine)

# load pre-trained model into bidi-lstm network
param = "./two_stream_lstm_models/pass-00000"
network.loadParameters(param)

converter = DataProviderConverter([dense_vector(1024, seq_type=SequenceType.SEQUENCE), dense_vector(128, seq_type=SequenceType.SEQUENCE), sparse_binary_vector(4716,seq_type=SequenceType.NO_SEQUENCE)])
[rgb_feat, audio_feat, label] = _generate_test_data('/media/data/train/train-0.pkl', 0)

inArg = converter([[rgb_feat, audio_feat, [label]]])
network.forwardTest(inArg)
output_layer = "__bidirectional_lstm_0__"
output = network.getLayerOutputs(output_layer)
res = output[output_layer]['value']

**Comment by CrossLee1** [comment]
我看了一下代码，没看出来什么问题。

**Comment by CrossLee1** [comment]
`converter = DataProviderConverter([dense_vector(1024, seq_type=SequenceType.SEQUENCE), dense_vector(128, seq_type=SequenceType.SEQUENCE)])`

`inArg = converter([[rgb_feat, audio_feat]])`

--------------------------------------------------------------
如要想要把label也传进去，可以在paddle的repo下咨询paddle的同学

**Comment by BroJackfeely** [comment]
您用的paddle版本？

**Comment by BroJackfeely** [comment]
已解决，在trainer_config.conf中将：
cost = multi_binary_label_cross_entropy(name='cost',input=output, label=label)
outputs(cost)
改为：
#cost = multi_binary_label_cross_entropy(name='cost',input=output, label=label)
outputs(output)

----------------------------------------------------------------------------------------------------------------
并在convert data时，按您上面的提示只传入rgb_feature和audio_feature，
“converter = DataProviderConverter([dense_vector(1024, seq_type=SequenceType.SEQUENCE), dense_vector(128, seq_type=SequenceType.SEQUENCE)])

inArg = converter([[rgb_feat, audio_feat]])”

非常感谢您的鼎力相助！！！祝工作顺利，生活开心！
