### ISSUE TITLE
Pre-trained model for Youtube-8M

### ISSUE THREAD

**Issue by estathop** [baidu/Youtube-8M#2]
Can you please provide a link for your pre-trained model for the kaggle Youtube-8M challenge ?

**Comment by CrossLee1** [comment]
@estathop Thanks for your interest, we have provided the fflstm model in `fast_forward_lstm_depth7`

**Comment by estathop** [comment]
thanks for your rapid answer, in order to understand how to evaluate it and use it, should I dig deep into the paddle framework ? Is there some sort of tutorial ? Your model testing description is quite vague

**Comment by CrossLee1** [comment]
I think you should figure out how PaddlePaddle works, then you will find it easy to test with the model and configuration.
Feel free to ask when you have other questions.
